name: CI/CD Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest  # Using Ubuntu as the base runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Alpine
        run: |
          # Use Alpine in a Docker container
          docker run --rm -v ${{ github.workspace }}:/app alpine:edge /bin/sh -c "
            apk add --no-cache \
              raylib \
              vlc \
              lua5.3 \
              dub \
              gcc \
              gdc \
              bash \
              alpine-sdk && \
            cd /app && \
            chmod +x ./build.sh && \
            ./build.sh
          "
